version: '3'

services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 127.0.0.7:8000
    volumes:
      - .:/my_app_dir 
    ports:
      - "8000:8000"
    depends_on:
      - db
  #mysql:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zeitplan
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - ../mysql:/var/lib/mysql
  
  adminer:
    image: adminer
    ports:
      - 8070:8080
    depends_on:
      - db
      