# Generated by Django 3.2 on 2022-08-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plantilla de horario',
                'verbose_name_plural': 'Plantillas de horario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.asignatura')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.grado')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoProfesorHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.horario')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.profesor')),
            ],
            options={
                'verbose_name': 'Estado de profesor en horario',
                'verbose_name_plural': 'Estados de profesor en horario',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='EstadoMateriaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.horario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.materia')),
            ],
            options={
                'verbose_name': 'Estado de materia en horario',
                'verbose_name_plural': 'Estados de materia en horario',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='EstadoGradoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.grado')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.horario')),
            ],
            options={
                'verbose_name': 'Estado de grado en horario',
                'verbose_name_plural': 'Estados de grado en horario',
                'ordering': ['estado'],
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.horario'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.materia'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.profesor'),
        ),
    ]
