# Generated by Django 3.2 on 2022-09-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_grado_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['activo', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['activo'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='estadogradohorario',
            options={'ordering': ['activo'], 'verbose_name': 'Estado de grado en horario', 'verbose_name_plural': 'Estados de grado en horario'},
        ),
        migrations.AlterModelOptions(
            name='estadomateriahorario',
            options={'ordering': ['activo'], 'verbose_name': 'Estado de materia en horario', 'verbose_name_plural': 'Estados de materia en horario'},
        ),
        migrations.AlterModelOptions(
            name='estadoprofesorhorario',
            options={'ordering': ['activo'], 'verbose_name': 'Estado de profesor en horario', 'verbose_name_plural': 'Estados de profesor en horario'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['activo', 'nombre'], 'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['activo', 'nombre'], 'verbose_name': 'Plantilla de horario', 'verbose_name_plural': 'Plantillas de horario'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['activo', 'nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['activo', 'nombre'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='estadogradohorario',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='estadomateriahorario',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='estadoprofesorhorario',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='state',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='estado',
            new_name='activo',
        ),
        migrations.AddField(
            model_name='horario',
            name='estado_del_horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EstadoAulaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.aula')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.horario')),
            ],
            options={
                'verbose_name': 'Estado de aula en horario',
                'verbose_name_plural': 'Estados de aula en horario',
                'ordering': ['activo'],
            },
        ),
    ]
