# Generated by Django 3.2 on 2022-09-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20220904_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='description',
            new_name='descripcion',
        ),
    ]
