# Generated by Django 3.2 on 2022-10-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_pregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='state',
            new_name='status_model',
        ),
        migrations.AddField(
            model_name='grado',
            name='status_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='status_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estadoaulahorario',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.aula'),
        ),
        migrations.AlterField(
            model_name='estadogradohorario',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.grado'),
        ),
        migrations.AlterField(
            model_name='estadomateriahorario',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.materia'),
        ),
        migrations.AlterField(
            model_name='estadoprofesorhorario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.profesor'),
        ),
    ]
