# Generated by Django 3.2 on 2022-10-16 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20221016_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='state',
            new_name='state_model',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='status_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadogradohorario',
            name='Domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadogradohorario',
            name='Jueves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadogradohorario',
            name='Lunes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadogradohorario',
            name='Martes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadogradohorario',
            name='Miercoles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadogradohorario',
            name='Sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadogradohorario',
            name='Viernes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadogradohorario',
            name='status_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='Domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='Jueves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='Lunes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='Martes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='Miercoles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='Sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='Viernes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='anotaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='cantidad_max_periodo',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='estadoprofesorhorario',
            name='status_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='Domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='Jueves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='Lunes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='Martes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='Miercoles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='Sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='Viernes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='duracion_hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horario',
            name='duracion_minuto',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(default='07:00:00'),
        ),
        migrations.AddField(
            model_name='horario',
            name='no_periodos',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='horario',
            name='status_model',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Recesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('periodo', models.IntegerField(default=None)),
                ('hora_duracion', models.IntegerField(default=0)),
                ('minuto_duracion', models.IntegerField(default=30)),
                ('status_model', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.horario')),
            ],
            options={
                'verbose_name': 'Receso',
                'verbose_name_plural': 'Recesos',
            },
        ),
        migrations.CreateModel(
            name='CondicionEstadoProfesorHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('dia', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio', models.IntegerField(default=0)),
                ('minuto_inicio', models.IntegerField(default=0)),
                ('hora_fin', models.IntegerField(default=0)),
                ('minuto_fin', models.IntegerField(default=0)),
                ('status_model', models.BooleanField(default=True)),
                ('estado_profesor_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.estadoprofesorhorario')),
            ],
            options={
                'verbose_name': 'Condicion de estado de profesor en horario',
                'verbose_name_plural': 'Condiciones de estado de profesor en horario',
                'ordering': ['activo'],
            },
        ),
        migrations.CreateModel(
            name='CondicionEstadoGradoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('dia', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio', models.IntegerField(default=0)),
                ('minuto_inicio', models.IntegerField(default=0)),
                ('hora_fin', models.IntegerField(default=0)),
                ('minuto_fin', models.IntegerField(default=0)),
                ('status_model', models.BooleanField(default=True)),
                ('estado_grado_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.estadogradohorario')),
            ],
            options={
                'verbose_name': 'Condicion de estado de grado en horario',
                'verbose_name_plural': 'Condiciones de estado de grado en horario',
                'ordering': ['activo'],
            },
        ),
    ]
