# Generated by Django 3.2 on 2022-10-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20221016_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoprofesorhorario',
            name='Domingo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estadoprofesorhorario',
            name='Sabado',
            field=models.BooleanField(default=True),
        ),
    ]
