# Generated by Django 3.2 on 2022-10-17 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20221017_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadomateriahorario',
            name='Domingo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadomateriahorario',
            name='Jueves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadomateriahorario',
            name='Lunes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadomateriahorario',
            name='Martes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadomateriahorario',
            name='Miercoles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadomateriahorario',
            name='Sabado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadomateriahorario',
            name='Viernes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estadogradohorario',
            name='Domingo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estadogradohorario',
            name='Sabado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estadoprofesorhorario',
            name='cantidad_max_periodo',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CondicionEstadoMateriaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('dia', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio', models.IntegerField(default=0)),
                ('minuto_inicio', models.IntegerField(default=0)),
                ('hora_fin', models.IntegerField(default=0)),
                ('minuto_fin', models.IntegerField(default=0)),
                ('status_model', models.BooleanField(default=True)),
                ('estado_materia_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.estadomateriahorario')),
            ],
            options={
                'verbose_name': 'Condicion de estado de materia en horario',
                'verbose_name_plural': 'Condiciones de estado de materia en horario',
                'ordering': ['activo'],
            },
        ),
    ]
