# Generated by Django 3.2 on 2022-10-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20221017_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='anotaciones_asignatura',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
