# Generated by Django 3.2 on 2022-10-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_horario_anotaciones_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.estadomateriahorario'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.estadoprofesorhorario'),
        ),
    ]
