# Generated by Django 3.2 on 2022-10-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_periodoshorario_versioneshorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoshorario',
            name='no_periodo',
            field=models.IntegerField(default=1),
        ),
    ]
