# Generated by Django 3.2 on 2022-10-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_periodoshorario_no_periodo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VersionesHorario',
            new_name='VersionHorario',
        ),
    ]
