# Generated by Django 3.2 on 2022-10-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_rename_versioneshorario_versionhorario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeriodosHorario',
            new_name='PeriodoHorario',
        ),
    ]
