# Generated by Django 3.2 on 2022-10-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_periodohorario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='type',
            field=models.CharField(default='Periodo', max_length=50),
        ),
    ]
